### ISSUE TITLE
Socrata WebJob doesn't meet new SNI requirement

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/analytics.smgov.net#42]
**Background:** [SNI now required for HTTPS connections](https://dev.socrata.com/changelog/2016/08/24/sni-now-required-for-https-connections.html) and socrata/discuss#30

**Error:** We're now seeing failures in the `socrata` WebJob, with the following output

```
[08/31/2016 08:30:04 > 4f9adc: SYS INFO] Status changed to Initializing
[08/31/2016 08:30:04 > 4f9adc: SYS INFO] Run script 'run.py' with script host - 'PythonScriptHost'
[08/31/2016 08:30:04 > 4f9adc: SYS INFO] Status changed to Running
[08/31/2016 08:30:21 > 4f9adc: ERR ] D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\requests\packages\urllib3\util\ssl_.py:318: SNIMissingWarning: 
An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS 
is not available on this platform. This may cause the server to present an incorrect TLS certificate, 
which can cause validation failures. You can upgrade to a newer version of Python to solve this. 
For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
[08/31/2016 08:30:21 > 4f9adc: ERR ]   SNIMissingWarning
[08/31/2016 08:30:21 > 4f9adc: ERR ] D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning:
A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately
and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to 
solve this. For more information, see
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
[08/31/2016 08:30:21 > 4f9adc: ERR ]   InsecurePlatformWarning
[08/31/2016 08:30:21 > 4f9adc: ERR ] Traceback (most recent call last):
[08/31/2016 08:30:21 > 4f9adc: ERR ]   File "run.py", line 78, in <module>
[08/31/2016 08:30:21 > 4f9adc: ERR ]     soda_client.upsert(os.environ["SOCRATA_RESOURCEID"], chunk)
[08/31/2016 08:30:21 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\sodapy\__init__.py", line 222, in upsert
[08/31/2016 08:30:21 > 4f9adc: ERR ]     return self._perform_update("post", resource, payload)
[08/31/2016 08:30:21 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\sodapy\__init__.py", line 239, in _perform_update
[08/31/2016 08:30:21 > 4f9adc: ERR ]     data=json.dumps(payload))
[08/31/2016 08:30:21 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\sodapy\__init__.py", line 281, in _perform_request
[08/31/2016 08:30:21 > 4f9adc: ERR ]     response = getattr(self.session, request_type)(uri, **kwargs)
[08/31/2016 08:30:21 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\requests\sessions.py", line 518, in post
[08/31/2016 08:30:21 > 4f9adc: ERR ]     return self.request('POST', url, data=data, json=json, **kwargs)
[08/31/2016 08:30:21 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\requests\sessions.py", line 475, in request
[08/31/2016 08:30:21 > 4f9adc: ERR ]     resp = self.send(prep, **send_kwargs)
[08/31/2016 08:30:22 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\requests\sessions.py", line 585, in send
[08/31/2016 08:30:22 > 4f9adc: ERR ]     r = adapter.send(request, **kwargs)
[08/31/2016 08:30:22 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\requests\adapters.py", line 477, in send
[08/31/2016 08:30:22 > 4f9adc: ERR ]     raise SSLError(e, request=request)
[08/31/2016 08:30:22 > 4f9adc: ERR ] requests.exceptions.SSLError: hostname 'data.smgov.net' doesn't match 'wxyz.example.org'
[08/31/2016 08:30:22 > 4f9adc: SYS INFO] Status changed to Failed
[08/31/2016 08:30:22 > 4f9adc: SYS ERR ] Job failed due to exit code 1
```

**Possible solution:** (if we are stuck with this version of Python) socrata/dev.socrata.com#594 and [this SO post](https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484)

**Comment by thekaveman** [comment]
Also could be solved by #32

**Comment by thekaveman** [comment]
[Another possible solution](http://stackoverflow.com/a/33427176/453168) to use Python 3 in Azure WebJobs

**Comment by thekaveman** [comment]
@allejo I think I have a solution for this - I tried the approach from [this SO answer](http://stackoverflow.com/a/33427176/453168) on a test Web App, and it worked. So I'm going to rework the `socrata` job to do the same and we'll see.

**Comment by allejo** [comment]
Sounds good

**Comment by thekaveman** [comment]
Take a look at that commit and let me know what you think - we can always spin up a test instance/slot to deploy that branch and check it out live

**Comment by allejo** [comment]
Travis creates the Python virtual environment for us and is using python 2.7.x so 3.4.x isn't created at the moment. I think Travis needs to be configured to use that

**Comment by thekaveman** [comment]
Hmmm, I'm not that familiar with configuring Travis. If you'd like to take this and run go for it!

**Comment by allejo** [comment]
Sure thing. I'll also add more notes to the README regarding that

**Comment by allejo** [comment]
@thekaveman Care to take a look at my changes? Also, can this be tested in a test Azure instance before it's deployed? Just make sure it works as expect with 3.4

**Comment by thekaveman** [comment]
@allejo Looks OK to me, though I haven't thoroughly read up on what is different from Python 2.x --> 3.x e.g. the changes to arguments of `open(...)`. I'm sure you got it :smile: 

I setup a "slot" in the azure app that we should be able to deploy to. I'll be modifying the `.travis.yml` to target this slot temporarily so we can test.

**Comment by thekaveman** [comment]
Ok, not sure what's going on. 
My change is here ccc5d50 - Travis is running through its process _almost_ correctly [see build log](https://travis-ci.org/CityofSantaMonica/analytics.smgov.net/builds/157955630) 

This output towards the end (starting at [line 1964](https://travis-ci.org/CityofSantaMonica/analytics.smgov.net/builds/157955630#L1964)):

```
Deploying application
Deploying to Azure Web App 'csmanalytics-stage'
Already up-to-date!
```

says that nothing is actually sent to Azure. On the Azure side, we see `.kudu/deploy.sh` fail because the `_site` folder doesn't exist:

```
Command: bash .kudu/deploy.sh
Using custom deployment setting for DEPLOYMENT_SOURCE custom value is '_site'.
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository\_site' to: 'D:\home\site\wwwroot'
Error: Could not find a part of the path 'D:\home\site\repository\_site'.
An error has occurred during web site deployment.
Kudu Sync failed
Error: Could not find a part of the path 'D:\home\site\repository\_site'.
D:\Program Files (x86)\SiteExtensions\Kudu\57.50831.2397\bin\Scripts\starter.cmd bash .kudu/deploy.sh
```

**Comment by allejo** [comment]
Does the Azure slot have an already existing git repo with a history? If you FTP into the slot, does the repository folder `D:\home\site\repository` have anything inside?

**Comment by thekaveman** [comment]
More info:

I had incorrectly setup the Azure slot to connect to the GitHub repo for deployment, but we want a local git repo that Travis pushes to. That has been updated. **(0)**

There's an Azure setting that says which branch should be used for deployment, and it defaults to `master`. I updated that setting for the slot to be our `webjob-refactor` branch. **(1)** 

If we look at `D:\home\site\repository` in the slot, we do see a git repo (but nothing else):

```
D:\home\site\repository>ls -alF
total 4
drwxr-xr-x 1 Unknown+User Unknown+Group 0 Sep  6 18:35 ./
drwxr-xr-x 1 Unknown+User Unknown+Group 0 Sep  6 18:35 ../
drwxr-xr-x 1 Unknown+User Unknown+Group 0 Sep  6 19:02 .git/
```

There is no history, and no branches other than `master`:

```
D:\home\site\repository>git status
On branch master

Initial commit

nothing to commit (create/copy files and use "git add" to track)

D:\home\site\repository>git show-branch --all
No revs to be shown.
```

Then I came across [the code that Travis uses for Azure deployment](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/azure_webapps.rb#L30) which seems to hardcode pushing to the remote's `master` branch. So I undid the setting from **(1)** above.

After re-running that [same Travis build](https://travis-ci.org/CityofSantaMonica/analytics.smgov.net/builds/157955630), we get the same output on the Travis side (i.e. `Already up-to-date!`). The deploy isn't even making it to Azure, that seemed to be a red-herring from my previously screwed up settings in Azure **(0)**.

**Comment by thekaveman** [comment]
See also: travis-ci/dpl#438, we may be in that situation.

**Comment by allejo** [comment]
Well that's certainly limiting and bothersome... Can we just manually push a built site to the test slot? The built site would need the compiled Jekyll source and the virtual python environment.

**Comment by thekaveman** [comment]
Oh come on, don't you want to solve this totally unrelated problem instead of focusing on our actual issue :dizzy_face: 

Great idea, I'll try that next.

**Comment by thekaveman** [comment]
@allejo:

I finally got the compiled version of this branch deployed to our test slot in Azure. Good and bad news:

**Good:** the changes to `aggregate` look good (had to add the `run.cmd` file to select Python3)

**Bad (not really):** The `socrata` job is still failing, although with a completely different error message. It's unclear if we have resolved the SNI issues, because the program is failing before trying to call into `sodapy`:

```
[09/07/2016 19:02:27 > a365ba: INFO] D:\local\Temp\jobs\triggered\socrata\hjbjn5vd.vez>D:\Python34\python job.py 
[09/07/2016 19:02:28 > a365ba: ERR ]   File "job.py", line 77
[09/07/2016 19:02:28 > a365ba: ERR ]     upsert_chunks = [ data['data'][x:x+soda_batch_size] for x in range(0, len(data['data']), soda_batch_size) ]
[09/07/2016 19:02:28 > a365ba: ERR ]                 ^
[09/07/2016 19:02:28 > a365ba: ERR ] SyntaxError: invalid syntax
[09/07/2016 19:02:29 > a365ba: SYS INFO] Status changed to Failed
[09/07/2016 19:02:29 > a365ba: SYS ERR ] Job failed due to exit code 1
```
